### ISSUE TITLE
Quick Yes/No Poll

### ISSUE THREAD

**Issue by joshua-igor** [mclemente/foundryvtt-easy-polls#1]
Since the majority of players are playing with voice chat, it would be interesting to have a option for the DM to do a Quick Yes/No Poll.
Scenario: The players are discussing if they should kill or spare a NPC. The GM decides to create a poll saying on the voice chat: "Vote "Yes" to kill and "No" to spare". The DM would then create a quick poll with just Yes/No options for the players to vote.
Currently, the DM would need to type:

```
/p Poll:
Yes
No
```

With this system there would be a chat command that would automatically type this. Example: "/p-yn" would output the same as the previous command.
A similar thing can be made using Macros, but it would be interesting to have this natively.

**Comment by mclemente** [comment]
Update and try it.

`/p-yn`, `/poll-yn` (and variants with space) should work.
