### ISSUE TITLE
[BUG] Não tem diferença secreto de aberto

### ISSUE THREAD

**Issue by brunocalado** [mclemente/foundryvtt-easy-polls#3]
Oi.

Não consegui perceber a diferença entre o voto secreto do aberto. Qual é? No aberto não deveria mostrar qual jogador votou no que?

![image](https://user-images.githubusercontent.com/4999783/177064337-8912fad4-1085-4118-9033-3665e83acf15.png)

**Comment by mclemente** [comment]
O voto aberto adiciona um atributo `title` em cada opção listando quem votou nela https://github.com/mclemente/foundryvtt-easy-polls/blob/master/templates/poll.html#L10-L12

**Comment by brunocalado** [comment]
Eu não estou conseguindo achar isso no chat.

Acessei como 2 usuarios extras, votei, mas não vejo o nome dos usuários.

https://user-images.githubusercontent.com/4999783/177160371-8d3d181d-6d24-4a36-954c-09fe35627653.mp4
