### ISSUE TITLE
[BUG] Licença Estranha

### ISSUE THREAD

**Issue by brunocalado** [mclemente/foundryvtt-easy-polls#4]
Oi. Creative Commons Attribution 4.0 para código fonte é muito estranho. Não seria legal migrar para uma licença equivalente de código?

Easy Polls is a fork of [Forien's Easy Polls](https://github.com/Forien/foundryvtt-forien-easy-polls), used under [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). Easy Polls is licensed under [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/) by Matheus Clemente.

**Comment by mclemente** [comment]
Eu tinha copiado direto da versão original. Consertei agora e coloquei MIT. Obrigado.
