### ISSUE TITLE
[BUG] v10 issue with lang

### ISSUE THREAD

**Issue by Jonwh25** [mclemente/foundryvtt-easy-polls#7]
**Module Version:** v1.2.1

**Describe the bug**
When installing it gives an error about lang/pt-BR.json not existing.

This is on v10 of foundry.

![image](https://user-images.githubusercontent.com/60674327/190829248-93519775-f5f1-482c-95a6-1d1d159e382d.png)

**Comment by mclemente** [comment]
Try reinstalling, it should be fixed now.
