### ISSUE TITLE
Macro Poll creation?

### ISSUE THREAD

**Issue by MarkPearce** [mclemente/foundryvtt-easy-polls#8]
My usecase is that i need to frequently run the same poll.  1/hour in my game the players vote to who should get a HeroPoint.

It would be cool to be able to have a preset poll, or a macro that I could click to trigger the same vote.

or even if easy-polls remembered it's last poll, so I wouldn't have to re-enter the options each time.

is the api there have a macro that sets up a poll?

**Comment by brunocalado** [comment]
Put this in a hot bar with type equal chat. 

```
/p Do you want to spend Hero Point?
Yes
No
Whatever
```
