### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by codeadsa** [mclemente/foundryvtt-easy-polls#9]
**Module Version:** v10 build 290
Pathfinder 2nd Edition: 4.3.4
Easy Polls: 1.3

**Describe the bug**
I've selected "Single Vote" but the player is able to select multiple values

**To Reproduce**
1. Type "/p-yn" in dialog box
2. On popup, Number of Votes: Single Vote is defaulted and selected. 
3. Click Create
4. On other browser logged in as a player I see the chat card with Yes and No checkboxes and I can click both

**Expected behavior**
The Yes/No boxes are radio buttons, or check boxes that only allow one item to be checked.

**Screenshots**
**![Uploading** image.png…]()
**Browser:**
 - 

**Foundry Version:** 

**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by mclemente** [comment]
Should be fixed now. Thanks for the report!

**Comment by codeadsa** [comment]
The toggle works Thanks. But the system that records the vote still keeps the item tallied. IE I have a poll with 2 items, if I switch between the radio box, only 1 is selected on the UI, but the results poll keeps both items recorded as if the user selected both.
